apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jfx4sdc9a-go
  janus-idp.io/tekton: jfx4sdc9a-go
  backstage.io/kubernetes-id: jfx4sdc9a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jfx4sdc9a-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
